### PR TITLE
20190101 global conf

### PR DESCRIPTION
**Pull request by nbastin**
Makes `castero.config.Config` available as a singleton so we don't have to pass it around to every instance that wants to use it.

### CODE REVIEW

**Comment by xgi** [comment]
I'm generally wary of singletons, especially static ones. I'm not fond of constantly referencing a static instance since I think it's both a crutch and also a bit hard to read. In addition, I'm not totally convinced that the config-passing was an issue. I somewhat recently made the config instance a property of the display class as an effort to 'pair' them when they are both used as arguments, but I found that there are times when you may need the config object without the display and I don't really think this change would help that.

To be honest, the current structure sort-of sets up the config class as a singleton since it is only instantiated in __main__. I just like that better because I can have it be more clearly "owned" by the display class.

I don't think I'll be merging these changes, but I'll leave this open for now since I may reconsider. Thanks for the help, and sorry for the inconvenience. (Also, if you would like to make broader changes like this in the future, it may be a good idea to create an Issue first to argue for your changes).

**Comment by nbastin** [comment]
I understand - that's why I started making issues.. :-)  We don't really have a good communication mechanism otherwise.

The reason I did this is because it *is* a singleton for all intents and purposes, but we have to modify method arguments to pass it to new places, and that means changing signatures in ways that are awkward.

For what it's worth this does help the problem of getting the config without `display`, since you can simply `import castero.config as config` in the module and have `config.Config` available to you, regardless of where you got called from.

**Comment by nbastin** [comment]
This currently passes all tests using pytest directly, I am not sure why coverage has this intermittent file descriptor problem.

**Comment by xgi** [comment]
(This PR should have been marked as merged rather than closed. My bad.)

I'll talk a little about why I decided to merge this. These aren't all responses to you, I just want to provide my personal perspective for potential posterity (:wink:).

My main concern was not with characterizing the config object as a singleton, but rather with making it a global instance. I'm generally very wary of global variables, and that hasn't changed in spite of these modifications. However, I think it's important when writing maintainable OOP to create reliable and expandable ownership structures. 

I'm accepting this change for two reasons:
1) Passing the config object between methods was cumbersome, and often even when using multiple instance methods in the same class, we would have to pass the config several times without maintaining a reference to its source. 
2) The ownership structure hasn't been threatened, because it doesn't really make sense for the config object to be owned by anything. I can see situations where we may want to access or modify the config without starting the display. In this sense, it is more reasonable for the config instance to be accessible by the module rather than through any parent container.

Thanks for the help!

**Pull request closed without merging**
